# Site
repository: elishakaranja/elishakaranja.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Elisha Karanja
title: Aspiring Full-Stack Developer
email: elishadominic74@gmail.com
phone: "+254 712 345 678" # Optional – remove or edit if you want
website: https://elishakaranja.github.io

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: elishakaranja
linkedin_username: elisha-karanja
twitter_username: elishathedev
instagram_username: elisha.codes

# Additional icon links
additional_links:
  - title: Resume
    icon: fas fa-file-alt
    url: https://example.com/resume.pdf
  - title: Portfolio
    icon: fas fa-laptop-code
    url: https://elishakaranja.github.io

# About Section
about_profile_image: images/profile.jpg
about_content: |
  I'm a passionate and curious software developer who loves building apps that solve real problems. Currently, I'm exploring the depths of Python and diving into React for building beautiful user interfaces.

  I thrive when turning ideas into interactive, user-friendly applications. Ask me about **APIs**, JavaScript, or how I turned a ticketing idea into a real app.

  In my free time, I enjoy reading about tech, helping friends debug code, and creating cool projects just for fun.

  Let's build something amazing together!

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Ticketi
        link: https://github.com/elishakaranja/ticketi
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/elishakaranja/ticketi
        quote: >
          A full-stack event ticketing platform with a twist
        description: |
          Ticketi allows users to create, buy, and resell event tickets at different pricing tiers (normal, off-peak, and peak). Built with React and Flask (in progress), it's all about user flexibility and event control.

      - layout: left
        border: weak
        title: Libro - Library Management CLI
        link: https://github.com/elishakaranja/libro-lms
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/elishakaranja/libro-lms
        quote: >
          A command-line library system
        description: |
          Libro is a command-line based library management system for organizing and tracking books and members. A simple but powerful app built with Python.

      - layout: left
        border: weak
        title: Ambulance Request App
        link: https://github.com/elishakaranja/ambulance-app
        link_text: View on GitHub
        additional_links:
          - title: GitHub Repository
            icon: fab fa-github
            url: https://github.com/elishakaranja/ambulance-app
        quote: >
          A collaborative web app for emergency ambulance requests
        description: |
          This app allows users to request ambulances and view available vehicles on a map. Built with React and Flask with a focus
